### PR TITLE
Making the cursor more visible

### PR DESCRIPTION
**Pull request by wistcc**
This closes https://github.com/sdras/night-owl-vscode-theme/issues/79

### CODE REVIEW

**Comment by wistcc** [comment]
I forgot to add a screenshot of the visual changes:

**Before**
image

**After**
image

**Comment by sdras** [comment]
Hm, though I really love that you spent time on this, (thank you so much for all the work you're doing here), I want to 
- keep the foreground of the selected item crisp, and 
- yes, I know it's a dull purple now, but I think when the value is in a higher key, the purple doesn't do well. I think this needs to become that blue color we use in other areas.

Thank you though!

**Comment by wistcc** [comment]
@sdras you mean that the cursor should be blue?

**Comment by sdras** [comment]
yes, like the sidebar foreground :) a bright shade of blue :)

**Comment by wistcc** [comment]
Ok, I can do that tonight if you haven't already! :)

**Comment by sdras** [comment]
If you don't mind taking it, that would be lovely! It's on my list but I have a ton of work for my job that's backed up right now. Much appreciated, Winner!

**Pull request closed without merging**
