### PR TITLE
Reduce specificity of selectors

### PR DESCRIPTION
**Pull request by andreluis-oliveira**
issue #319

issue #304

### CODE REVIEW

**Comment by lahirudx** [comment]
@sdras Could you please consider merging this pull request? I would really appreciate it, as I am eager to see these changes implemented. Thank you!

**Comment by sdras** [comment]
Can you please provide a screenshot of the changes? Thanks

**Comment by andreluis-oliveira** [comment]
> Can you please provide a screenshot of the changes? Thanks
 
https://github.com/sdras/night-owl-vscode-theme/issues/319#issuecomment-1528057055

**Comment by lahirudx** [comment]
Regarding issue #304
Before:
Screenshot 2024-12-28 at 2 42 06 PM

After:
Screenshot 2024-12-28 at 2 41 40 PM

**Comment by sdras** [comment]
Thank you!

**Pull request merged**
