### PR TITLE
fix: Adjusted color of bracket highlight in light theme

### LINKED ISSUE #331: [Version 2.1.0, Light] - changes to braces colors makes some braces hard to see
**2.0.2**: (Normal)
night-owl-pre-2 1

**2.1.0**: (Bad)
night-owl-2 1-bad-color

Looks like it's 222ca7c commit

### PR DESCRIPTION
**Pull request by CastaChick**
close #331 

Starting from version `2.1.0`, the contrast ratio of bracket highlights in light mode was lowered. We have adjusted this to match the display style of version `2.0.2`.

| version | screenshot |
| --- | --- |
| ver 2.0.2 |  |
| ver 2.1.0 |  |
| My suggestion | after |

### CODE REVIEW

**Comment by sdras** [comment]
Someone else mentioned this to me- I'll look into it soon

**Comment by sdras** [comment]
Actually, a little confused by your post above- in your suggestion screenshot, it looks the same as 2.1.0? What am I missing?

**Comment by CastaChick** [comment]
@sdras Apologies for the confusion.
As you can see in the enlarged image below, it seems that the brackets have become almost invisible in version 2.1.0.

| version | screenshot |
| --- | --- |
| ver 2.0.2 |  |
| ver 2.1.0 |  |
| My suggestion | after |

**Comment by abn5x** [comment]
I have the same issue. Almost invisible for me too..

**Comment by sdras** [comment]
Ah I see, thank you! I may revert the change from the last version rather than taking the PR because I've heard dark mode broke too, I'll get this in today

**Comment by CastaChick** [comment]
Thank you for reply. It would be better to revert the commit.
So, I will close this PR.
Have a great New Year✨

**Comment by sdras** [comment]
Thank you so much for this! This should be resolved now- I just published, might take an hour or two.

**Pull request closed without merging**
