### PR TITLE
"Fixed" the colors of the Dart files.

### PR DESCRIPTION
**Pull request by Jerobastian**

### CODE REVIEW

**Comment by Jerobastian** [comment]
Finally I fixed the colors of the C# and Dart files.

PD: Great tutorial! It was really easy to implement everything following it.

**Comment by sdras** [comment]
Can you please include the before and after screenshots? Thanks!

**Comment by Jerobastian** [comment]
Here they are:

## Dart (Flutter) - Before
Dart Before
## Dart (Flutter) - After
Dart After

## C# - Before
C# Before
## C# - After
C# After

**Comment by sdras** [comment]
This looks great, thank you.

**Pull request merged**
