### PR TITLE
Refactor invalid token colors

### LINKED ISSUE #218: Invalid / Deprecated scope not visible on `Night Owl Light`
TIL: The `align` attribute, which I commonly use in GitHub README's, is deprecated HTML.

It looks like the invalid/deprecated scope is `#ffffff`, which shows up fine on `Night Owl`:

Screen Shot 2019-07-04 at 1 26 16 PM

But on `Night Owl Light` it’s invisible, teehee!

Screen Shot 2019-07-04 at 1 25 55 PM

Here's the scope details...

Screen Shot 2019-07-04 at 1 19 53 PM

~I would’ve submitted a PR, but not sure how you want to handle this. Should deprecated attributes be styled differently?~ I noticed the color declarations were there, just assigned to `background` instead of `foreground` (which is not presently supported).

### PR DESCRIPTION
**Pull request by jlmakes**
Fixes #218 

Compare with this screenshot, where `align` is both visible and styled appropriately.

Screen Shot 2019-07-09 at 12 09 31 PM

### CODE REVIEW

**Comment by jlmakes** [comment]
**Note:** This is just for the light theme since it was _broken_, but similar improvements could be made to the dark theme as well. I can add similar fixes to this PR for the dark themes as well.

**Comment by jlmakes** [comment]
**Note:** This is just for the light theme since it was _broken_, but similar improvements could be made to the dark theme as well. All in good time! :)

**Comment by sdras** [comment]
`align` attribute is deprecated in HTML. Can you please post before/after screenshots of non-deprecated attributes? Thanks!

**Comment by jlmakes** [comment]
I only modified the invalid/deprecated scope, for the light theme.

**Before:**
Before

**After:**
After

As you can see, valid attributes are still blue… this only affects the deprecated attribute.

**Comment by sdras** [comment]
Thanks!

**Comment by sdras** [comment]
Can you please resolve the conflicts? Then I will merge. Thanks!

**Comment by macguirerintoul** [comment]
Hey @jlmakes, is this still open? I just ran into this issue myself.

**Comment by jlmakes** [comment]
I deleted the original fork. I'll apply the fix to the latest branch and open a new PR.

**Pull request closed without merging**
